version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - mongo_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - mongo_network
    command: ["mongod", "--config", "/etc/mongod.conf"]

volumes:
  mongodb_data:

networks:
  mongo_network:
    driver: bridge
