version: '3.8'
services:
  app:
    build: .
    container_name: appnode
    ports:
      - "3500:3500"
    volumes:
      - /usr/src/app/node_modules
    networks:
      - mongo_network
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      API_URL: https://pokeapi.co/api/v2/pokemon

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - mongo_network
    command: ["mongod", "--config", "/etc/mongod.conf"]

volumes:
  mongodb_data:

networks:
  mongo_network:
    driver: bridge
